### ISSUE TITLE
Feature: User can save recipes to their Recipe Book

### ISSUE THREAD

**Issue by cody-martin8** [cody-martin8/ajax-project#2]
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click or tap on a recipe in their search list to view the recipe. The recipes that are searched will have a title, image, list of ingredients, a link to the original recipe, and a Save button. The user can click Save Recipe, and the recipe will appear in their Recipe Book. After saving a recipe, the user will be navigated back to their search results.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Issue-2-Wireframe-Mobile](https://user-images.githubusercontent.com/96100245/182495416-4bc9c580-6c2c-40b4-99ad-fe358bda7cd8.png)
![Issue-2-Wireframe-Desktop-A](https://user-images.githubusercontent.com/96100245/182495434-95c5dd6f-0efb-4b2a-bd98-5ee1fdd56b87.png)
![Issue-2-Wireframe-Desktop-B](https://user-images.githubusercontent.com/96100245/182495437-e6ff3fd6-2cf4-4b7c-a7a2-2876d88f9b89.png)
![Issue-2-Wireframe-Desktop-C](https://user-images.githubusercontent.com/96100245/182495441-772abcf6-4025-469e-9b98-5b4606eda255.png)
![Issue-2-Wireframe-Desktop-D](https://user-images.githubusercontent.com/96100245/182495446-53a03295-7256-405e-9bba-177688c99cf4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Create page for Recipe Book
  - [x] Create a page header with the Recipe Book heading, a Search button and a Create button
  - [x] Place an unordered list on the page to receive DOM trees of the recipes
    - [x] Create some dummy entries for formatting (image, title, and Options icon
- [x] Recipes link at top of page redirects to Recipe Book page
- [x] Search button redirects to the Search New Recipes page
- [x] Clicking on recipes in Search New Recipes page opens New Recipe page
  - [x] Create empty New Recipe page (which is populated with a DOM tree of a recipe)
  - [x] Create dummy New Recipe page for formatting
    - [x] Link to recipe source should work
    - [x] Save Recipe button saves the recipe to the Recipe book
      - [x] Store recipe information in data object 
      - [x] Redirect user to Search New Recipes page
      - [x] Use data object to populate Recipe book
